x-common-environment: &common-environment
  RUST_LOG: INFO
  DISCORD_TOKEN: $DISCORD_TOKEN
  OVERRIDE_USER_ID: $OVERRIDE_USER_ID
  OVERRIDE_USER_NAME: $OVERRIDE_USER_NAME
  GUILD_ID: $GUILD_ID
  SYSTEM_PROMPT: $SYSTEM_PROMPT
  MODEL_NAME: $MODEL_NAME
  OLLAMA_HOST: $OLLAMA_HOST
  OLLAMA_PORT: $OLLAMA_PORT
  ERROR_OLLAMA_ERROR: $ERROR_OLLAMA_ERROR
  ERROR_NO_MESSAGES: $ERROR_NO_MESSAGES
  TRIGGER_WORDS: $TRIGGER_WORDS
  TABLE_HEADER: $TABLE_HEADER
  TELOXIDE_TOKEN: $TELOXIDE_TOKEN

services:
  discord-bot:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        WORKDIR /app
        RUN apt-get update && apt-get install -y \
            libssl3 \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        CMD ["./bin/discord-bot"]
    container_name: discord-bot
    volumes:
      - ./.config:/app/.config:rw
      - ./bin:/app/bin:ro
      - ./exchange:/app/exchange:rw
      - ./stat:/app/stat:rw
    restart: unless-stopped
    networks:
      - bot-network
    environment:
      <<: *common-environment

  telegram-bot:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        WORKDIR /app
        RUN apt-get update && apt-get install -y \
            libssl3 \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        CMD ["./bin/telegram-bot"]
    container_name: telegram-bot
    volumes:
      - ./.config:/app/.config:rw
      - ./bin:/app/bin:ro
      - ./exchange:/app/exchange:rw
    restart: unless-stopped
    networks:
      - bot-network
    environment:
      <<: *common-environment

  kemono-ingester:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        WORKDIR /app
        RUN apt-get update && apt-get install -y \
            libssl3 \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*
        CMD ["./bin/kemono-ingester"]
    container_name: kemono-ingester
    volumes:
      - ./.config:/app/.config:rw
      - ./bin:/app/bin:ro
      - ./exchange:/app/exchange:rw
    restart: unless-stopped
    networks:
      - bot-network
    environment:
      <<: *common-environment

networks:
  bot-network:
    driver: bridge
