[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
